name: Generic formatter
on: [pull_request]
jobs:
  call_go_fmt:
    if: ${{ vars.FORMAT_GO == 'true' }}
    uses: Sample-Ganes-Org/required_workflow_repo/.github/workflows/go-fmt.yml@main
  
  call_prettier_js:
    if: ${{ vars.PRETTIFY_JS == 'true' }}
    uses: Sample-Ganes-Org/required_workflow_repo/.github/workflows/prettier-js.yml@main
  
  call_prettier_md:
    if: ${{ vars.PRETTIFY_MD == 'true' }}
    uses: Sample-Ganes-Org/required_workflow_repo/.github/workflows/prettier-md.yml@main
  
  job_to_fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
