name: Go fmt
on: [pull_request]
jobs:
  gofmt:
    name: Go fmt
    runs-on: ubuntu-latest
    container:
      image: golang:1.16.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ vars.REPO_GO_PATH }}

      - name: Run Lint
        env:
          GOPATH: ./go
        run: |
          echo ${{vars.REPO_GO_PATH}}
        working-directory: $ {{ vars.REPO_GO_PATH }}
