name: Go fmt
on: [pull_request]
jobs:
  gofmt:
    name: Go fmt
    runs-on: ubuntu-latest

    steps:
      - name: Install go ${{ vars.REPO_GOLANG_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: '${{ vars.REPO_GOLANG_VERSION }}'
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./go/src/${{vars.REPO_WORKING_DIRECTORY}}
          
#       - name: Format
#         run: |
#           gofmt -s -l . | wc -l
#         working-directory: ./go/src/${{vars.REPO_WORKING_DIRECTORY}}

      - name: Run Lint
        env:
          GOPATH: /home/runner/work/${{vars.REPO_NAME}}/${{vars.REPO_NAME}}/go
        run: |
          go list ./...
          files=$(go list ./... 2>/dev/null | grep -v ./tmp | grep -v hydro | sed -Ee "s|github.com/github/go-sample-service/?|./|" | xargs -I {} find {} -type f -name '*.go' ! -name '*.pb.go' ! -name '*.twirp.go' ! -name 'mock_*.go')
          echo $files
        working-directory: ./go/src/${{vars.REPO_WORKING_DIRECTORY}}
