name: Go fmt
on: [pull_request]
jobs:
  gofmt:
    name: Go fmt
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.REPO_GOLANG_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./go/src/${{vars.REPO_WORKING_DIRECTORY}}

      - name: Run Lint
        env:
          GOPATH: ./go
        run: |
          pwd
          scripts="$(dirname "$0")"
          root="$(dirname "$scripts")"
          cd -P "$root"
          pwd
          echo ./go/src/${{vars.REPO_WORKING_DIRECTORY}}
        working-directory: ./go/src/${{vars.REPO_WORKING_DIRECTORY}}
